---
- hosts: imageservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # https://twitter.com/matsuu/status/773105183744069633
    - replace: dest=/home/isucon/.xbuild/perl-install regexp='http://cpanmin\.us/' replace='http://git.io/cpanm'
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.3.0 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # golang
    - command: /home/isucon/.xbuild/go-install 1.8 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go

- hosts: imageservers
  sudo: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
